<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    public function run()
    {
        DB::table('municipios')->insert([
            ['id' => 1, 'nome' => 'Rio Branco', 'estado_id' => 1],
            ['id' => 2, 'nome' => 'Cruzeiro do Sul', 'estado_id' => 1],
            ['id' => 3, 'nome' => 'Sena Madureira', 'estado_id' => 1],
            ['id' => 4, 'nome' => 'Tarauacá', 'estado_id' => 1],
            ['id' => 5, 'nome' => 'Feijó', 'estado_id' => 1],
            ['id' => 6, 'nome' => 'Maceió', 'estado_id' => 2],
            ['id' => 7, 'nome' => 'Arapiraca', 'estado_id' => 2],
            ['id' => 8, 'nome' => 'Rio Largo', 'estado_id' => 2],
            ['id' => 9, 'nome' => 'Palmeira dos Índios', 'estado_id' => 2],
            ['id' => 10, 'nome' => 'União dos Palmares', 'estado_id' => 2],
            ['id' => 11, 'nome' => 'Macapá', 'estado_id' => 3],
            ['id' => 12, 'nome' => 'Santana', 'estado_id' => 3],
            ['id' => 13, 'nome' => 'Laranjal do Jari', 'estado_id' => 3],
            ['id' => 14, 'nome' => 'Oiapoque', 'estado_id' => 3],
            ['id' => 15, 'nome' => 'Porto Grande', 'estado_id' => 3],
            ['id' => 16, 'nome' => 'Manaus', 'estado_id' => 4],
            ['id' => 17, 'nome' => 'Parintins', 'estado_id' => 4],
            ['id' => 18, 'nome' => 'Itacoatiara', 'estado_id' => 4],
            ['id' => 19, 'nome' => 'Manacapuru', 'estado_id' => 4],
            ['id' => 20, 'nome' => 'Coari', 'estado_id' => 4],
            ['id' => 21, 'nome' => 'Salvador', 'estado_id' => 5],
            ['id' => 22, 'nome' => 'Feira de Santana', 'estado_id' => 5],
            ['id' => 23, 'nome' => 'Vitória da Conquista', 'estado_id' => 5],
            ['id' => 24, 'nome' => 'Camaçari', 'estado_id' => 5],
            ['id' => 25, 'nome' => 'Itabuna', 'estado_id' => 5],
            ['id' => 26, 'nome' => 'Fortaleza', 'estado_id' => 6],
            ['id' => 27, 'nome' => 'Caucaia', 'estado_id' => 6],
            ['id' => 28, 'nome' => 'Juazeiro do Norte', 'estado_id' => 6],
            ['id' => 29, 'nome' => 'Maracanaú', 'estado_id' => 6],
            ['id' => 30, 'nome' => 'Sobral', 'estado_id' => 6],
            ['id' => 31, 'nome' => 'Brasília', 'estado_id' => 7],
            ['id' => 32, 'nome' => 'Vitória', 'estado_id' => 8],
            ['id' => 33, 'nome' => 'Vila Velha', 'estado_id' => 8],
            ['id' => 34, 'nome' => 'Serra', 'estado_id' => 8],
            ['id' => 35, 'nome' => 'Cariacica', 'estado_id' => 8],
            ['id' => 36, 'nome' => 'Linhares', 'estado_id' => 8],
            ['id' => 37, 'nome' => 'Goiânia', 'estado_id' => 9],
            ['id' => 38, 'nome' => 'Aparecida de Goiânia', 'estado_id' => 9],
            ['id' => 39, 'nome' => 'Anápolis', 'estado_id' => 9],
            ['id' => 40, 'nome' => 'Rio Verde', 'estado_id' => 9],
            ['id' => 41, 'nome' => 'Luziânia', 'estado_id' => 9],
            ['id' => 42, 'nome' => 'São Luís', 'estado_id' => 10],
            ['id' => 43, 'nome' => 'Imperatriz', 'estado_id' => 10],
            ['id' => 44, 'nome' => 'São José de Ribamar', 'estado_id' => 10],
            ['id' => 45, 'nome' => 'Timon', 'estado_id' => 10],
            ['id' => 46, 'nome' => 'Caxias', 'estado_id' => 10],
            ['id' => 47, 'nome' => 'Cuiabá', 'estado_id' => 11],
            ['id' => 48, 'nome' => 'Várzea Grande', 'estado_id' => 11],
            ['id' => 49, 'nome' => 'Rondonópolis', 'estado_id' => 11],
            ['id' => 50, 'nome' => 'Sinop', 'estado_id' => 11],
            ['id' => 51, 'nome' => 'Tangará da Serra', 'estado_id' => 11],
            ['id' => 52, 'nome' => 'Campo Grande', 'estado_id' => 12],
            ['id' => 53, 'nome' => 'Dourados', 'estado_id' => 12],
            ['id' => 54, 'nome' => 'Três Lagoas', 'estado_id' => 12],
            ['id' => 55, 'nome' => 'Corumbá', 'estado_id' => 12],
            ['id' => 56, 'nome' => 'Ponta Porã', 'estado_id' => 12],
            ['id' => 57, 'nome' => 'Belo Horizonte', 'estado_id' => 13],
            ['id' => 58, 'nome' => 'Uberlândia', 'estado_id' => 13],
            ['id' => 59, 'nome' => 'Contagem', 'estado_id' => 13],
            ['id' => 60, 'nome' => 'Juiz de Fora', 'estado_id' => 13],
            ['id' => 61, 'nome' => 'Betim', 'estado_id' => 13],
            ['id' => 62, 'nome' => 'Belém', 'estado_id' => 14],
            ['id' => 63, 'nome' => 'Ananindeua', 'estado_id' => 14],
            ['id' => 64, 'nome' => 'Santarém', 'estado_id' => 14],
            ['id' => 65, 'nome' => 'Marabá', 'estado_id' => 14],
            ['id' => 66, 'nome' => 'Parauapebas', 'estado_id' => 14],
            ['id' => 67, 'nome' => 'João Pessoa', 'estado_id' => 15],
            ['id' => 68, 'nome' => 'Campina Grande', 'estado_id' => 15],
            ['id' => 69, 'nome' => 'Santa Rita', 'estado_id' => 15],
            ['id' => 70, 'nome' => 'Patos', 'estado_id' => 15],
            ['id' => 71, 'nome' => 'Bayeux', 'estado_id' => 15],
            ['id' => 72, 'nome' => 'Curitiba', 'estado_id' => 16],
            ['id' => 73, 'nome' => 'Londrina', 'estado_id' => 16],
            ['id' => 74, 'nome' => 'Maringá', 'estado_id' => 16],
            ['id' => 75, 'nome' => 'Ponta Grossa', 'estado_id' => 16],
            ['id' => 76, 'nome' => 'Cascavel', 'estado_id' => 16],
            ['id' => 77, 'nome' => 'Recife', 'estado_id' => 17],
            ['id' => 78, 'nome' => 'Jaboatão dos Guararapes', 'estado_id' => 17],
            ['id' => 79, 'nome' => 'Olinda', 'estado_id' => 17],
            ['id' => 80, 'nome' => 'Caruaru', 'estado_id' => 17],
            ['id' => 81, 'nome' => 'Petrolina', 'estado_id' => 17],
            ['id' => 82, 'nome' => 'Teresina', 'estado_id' => 18],
            ['id' => 83, 'nome' => 'Parnaíba', 'estado_id' => 18],
            ['id' => 84, 'nome' => 'Picos', 'estado_id' => 18],
            ['id' => 85, 'nome' => 'Piripiri', 'estado_id' => 18],
            ['id' => 86, 'nome' => 'Floriano', 'estado_id' => 18],
            ['id' => 87, 'nome' => 'Rio de Janeiro', 'estado_id' => 19],
            ['id' => 88, 'nome' => 'São Gonçalo', 'estado_id' => 19],
            ['id' => 89, 'nome' => 'Duque de Caxias', 'estado_id' => 19],
            ['id' => 90, 'nome' => 'Nova Iguaçu', 'estado_id' => 19],
            ['id' => 91, 'nome' => 'Niterói', 'estado_id' => 19],
            ['id' => 92, 'nome' => 'Natal', 'estado_id' => 20],
            ['id' => 93, 'nome' => 'Mossoró', 'estado_id' => 20],
            ['id' => 94, 'nome' => 'Parnamirim', 'estado_id' => 20],
            ['id' => 95, 'nome' => 'São Gonçalo do Amarante', 'estado_id' => 20],
            ['id' => 96, 'nome' => 'Macaíba', 'estado_id' => 20],
            ['id' => 97, 'nome' => 'Porto Alegre', 'estado_id' => 21],
            ['id' => 98, 'nome' => 'Caxias do Sul', 'estado_id' => 21],
            ['id' => 99, 'nome' => 'Pelotas', 'estado_id' => 21],
            ['id' => 100, 'nome' => 'Canoas', 'estado_id' => 21],
            ['id' => 101, 'nome' => 'Santa Maria', 'estado_id' => 21],
            ['id' => 102, 'nome' => 'Porto Velho', 'estado_id' => 22],
            ['id' => 103, 'nome' => 'Ji-Paraná', 'estado_id' => 22],
            ['id' => 104, 'nome' => 'Ariquemes', 'estado_id' => 22],
            ['id' => 105, 'nome' => 'Vilhena', 'estado_id' => 22],
            ['id' => 106, 'nome' => 'Cacoal', 'estado_id' => 22],
            ['id' => 107, 'nome' => 'Boa Vista', 'estado_id' => 23],
            ['id' => 108, 'nome' => 'Rorainópolis', 'estado_id' => 23],
            ['id' => 109, 'nome' => 'Caracaraí', 'estado_id' => 23],
            ['id' => 110, 'nome' => 'Alto Alegre', 'estado_id' => 23],
            ['id' => 111, 'nome' => 'Pacaraima', 'estado_id' => 23],
            ['id' => 112, 'nome' => 'Florianópolis', 'estado_id' => 24],
            ['id' => 113, 'nome' => 'Joinville', 'estado_id' => 24],
            ['id' => 114, 'nome' => 'Blumenau', 'estado_id' => 24],
            ['id' => 115, 'nome' => 'São José', 'estado_id' => 24],
            ['id' => 116, 'nome' => 'Criciúma', 'estado_id' => 24],
            ['id' => 117, 'nome' => 'São Paulo', 'estado_id' => 25],
            ['id' => 118, 'nome' => 'Guarulhos', 'estado_id' => 25],
            ['id' => 119, 'nome' => 'Campinas', 'estado_id' => 25],
            ['id' => 120, 'nome' => 'São Bernardo do Campo', 'estado_id' => 25],
            ['id' => 121, 'nome' => 'Santo André', 'estado_id' => 25],
            ['id' => 122, 'nome' => 'Aracaju', 'estado_id' => 26],
            ['id' => 123, 'nome' => 'Nossa Senhora do Socorro', 'estado_id' => 26],
            ['id' => 124, 'nome' => 'Lagarto', 'estado_id' => 26],
            ['id' => 125, 'nome' => 'Itabaiana', 'estado_id' => 26],
            ['id' => 126, 'nome' => 'São Cristóvão', 'estado_id' => 26],
            ['id' => 127, 'nome' => 'Palmas', 'estado_id' => 27],
            ['id' => 128, 'nome' => 'Araguaína', 'estado_id' => 27],
            ['id' => 129, 'nome' => 'Gurupi', 'estado_id' => 27],
            ['id' => 130, 'nome' => 'Porto Nacional', 'estado_id' => 27],
            ['id' => 131, 'nome' => 'Paraíso do Tocantins', 'estado_id' => 27],
        ]);
    }
}
